<style>
html, body, #map_canvas {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
}
#map_canvas {
    position: relative;
}
body {
     
        font-family: 'Open Sans', sans-serif;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
</style>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<?php

//*********************************************
// Database stuff - all done with PHP
//*********************************************

// STEP 1: Connect to the database 
// Don't forget to fill in your own:
//  username, password and database name)

$db = new mysqli("localhost", "winterma_mark1","dinger", "winterma_tnd");
if (mysqli_connect_errno()) {
    printf("Connect failed: %s\n", mysqli_connect_error());
    exit();
}
  
// STEP 2: Query the table with the marker information

$res = $db->query("select * from Place");
  
// STEP 3: Store the marker info in arrays for each row found
// save the count of markers for later

$mrk_cnt = 0;
while ($obj = $res->fetch_object())  // get all rows (markers)
{
    $lat[$mrk_cnt] = $obj->lat;  // save the lattitude
    $lng[$mrk_cnt] = $obj->lng;  // save the longitude
    $inf[$mrk_cnt] = $obj->Name;  // save the info-window
    $mrk_cnt++;                      // increment the marker counter
}
$res->close();
// Now we have the lattitude, longitude and info-window text for each marker 
// stored in php arrays. Now we need to write the marker's JavaScript 
// dynamically with this information
include('config.php');
# connect mysql db
dbConnect();
$query = "SELECT * FROM `Place` Order by ID Desc ";
//$query = "SELECT * FROM `Place` INNER JOIN phpro_users ON Place.phpro_user_id = phpro_users.phpro_user_id where Place.phpro_user_id = '".$_GET["ID"]."'  Order by ID Desc ";
$countlast10 = mysql_query("SELECT * FROM  `Place` WHERE  `Date Added` >= DATE( NOW( ) ) - INTERVAL 7 DAY LIMIT 0 , 30 ");
$count_rows = mysql_num_rows($countlast10);
?>

<script type='text/javascript'>
var point;
var mrktx;
function load() {
   addTo = 0;
   var latlng = new google.maps.LatLng(37.775196, -122.419204);
   var myOptions = {
      zoom: 12,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
   };
   // NOTE: all values: latitude, longitude, zoom, etc.
   //       should also come from the database for flexibility
       
   var map = new google.maps.Map(document.getElementById("map_canvas"), 
              myOptions);
// This next block of JavaScript needs to be generated by PHP 
// to 'add-in' the information from the arrays

<?php
for ($lcnt = 0; $lcnt < $mrk_cnt; $lcnt++)
{
    
    echo "var point$lcnt = new google.maps.LatLng($lat[$lcnt], $lng[$lcnt]);\n";
    echo "var mrktx$lcnt = \"$inf[$lcnt]\";\n";
  echo "var infowindow$lcnt = new google.maps.InfoWindow({
        content: mrktx$lcnt
      });";
    echo "var marker$lcnt = new google.maps.Marker({position: point$lcnt, map: map});\n";
  echo "google.maps.event.addListener(marker$lcnt, 
         'mouseover', function() {
           infowindow$lcnt.open(map,marker$lcnt);
          });\n";
}
?>
}
</script>
</head>
<!DOCTYPE html>
<html>
  <head>
    <title>food.marksherrard.com</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="content-type" content="text/html; charset=UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
          
    <!-- CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="css/styles.css" rel="stylesheet" media="screen">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand" href="#">
             <img alt="Brand" src="images/icon.png" height="30px">
          </a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span>
 <span class="icon-bar"></span>
 <span class="icon-bar"></span>
 <span class="icon-bar"></span>

            </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            
            <ul class="nav navbar-nav">
                <li>
                    <a href="index.php" role="tab" data-toggle="tab">
                        List <span class="label label-success"><?php echo $count_rows ?></span>
                    </a>
                </li>
                <li><a href="map.php" role="tab" data-toggle="tab">Map</a>

                </li>
                
            </ul>
            <ul class="nav navbar-nav navbar-right" >
             <?php
                 if(!isset($_SESSION['user_id']))
                    {
                        ?>
                       <a type="button" class="btn btn-warning navbar-btn btn-block" href="login.php"> Login</a></a>
                        <?
                    }
                    else
                    {
                        ?>
                         <a type="button" class="btn btn-danger navbar-btn btn-block" href="add.php"> Add</a></a>
                         
                        <?
                  
                    }
                        ?>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

<body onload='load()'>

 <div id="map_canvas" style="width: 100%; height: 100%;margin: 0 0 0 0;"></div>
 

      

  
  

    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
     <script src="js/js.js"></script>
    
    <!--List.js-->
    <script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.1.1/list.min.js"></script>
    <script type="text/javascript">
    var options = {
    valueNames: [ 'name', 'area', 'type', 'date'  ]
};

var hackerList = new List('hacker-list', options);
    </script>
    <script type="text/javascript">
$('#menu-toggle').click(function(){
    $(this).find('i').toggleClass('glyphicon-chevron-up').toggleClass('glyphicon-chevron-down');
});
    </script>
     <script type="text/javascript">
$('#menu-toggle2').click(function(){
    $(this).find('i').toggleClass('glyphicon-chevron-up').toggleClass('glyphicon-chevron-down');
});
    </script>
  </body>
</html>