<?php
include ("connect.php");
include ("header.php"); 
?>
<style>
html, body, #map_canvas {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
}
#map_canvas {
    position: relative;
}
body {
     
        font-family: 'Open Sans', sans-serif;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
</style>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&amp;key=AIzaSyAyEwCPeqnt5XTgFRUOXF1VKabD5ho9Swo"></script>
<?php

//*********************************************
// Database stuff - all done with PHP
//*********************************************

// STEP 1: Connect to the database 
// Don't forget to fill in your own:
//  username, password and database name)

$db = new mysqli("localhost", "root","Dkeller12", "food");
if (mysqli_connect_errno()) {
    printf("Connect failed: %s\n", mysqli_connect_error());
    exit();
}
  
// STEP 2: Query the table with the marker information

$res = $db->query("select * from Place");
  
// STEP 3: Store the marker info in arrays for each row found
// save the count of markers for later

$mrk_cnt = 0;
while ($obj = $res->fetch_object())  // get all rows (markers)
{
    $lat[$mrk_cnt] = $obj->lat;  // save the lattitude
    $lng[$mrk_cnt] = $obj->lng;  // save the longitude
    $inf[$mrk_cnt] = $obj->Name;  // save the info-window
    $mrk_cnt++;                      // increment the marker counter
}
$res->close();
// Now we have the lattitude, longitude and info-window text for each marker 
// stored in php arrays. Now we need to write the marker's JavaScript 
// dynamically with this information
?>

<script type='text/javascript'>
var point;
var mrktx;
function load() {
   addTo = 0;
   var latlng = new google.maps.LatLng(37.775196, -122.419204);
   var myOptions = {
      zoom: 12,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
   };
   // NOTE: all values: latitude, longitude, zoom, etc.
   //       should also come from the database for flexibility
       
   var map = new google.maps.Map(document.getElementById("map_canvas"), 
              myOptions);
// This next block of JavaScript needs to be generated by PHP 
// to 'add-in' the information from the arrays

<?php
for ($lcnt = 0; $lcnt < $mrk_cnt; $lcnt++)
{
    
    echo "var point$lcnt = new google.maps.LatLng($lat[$lcnt], $lng[$lcnt]);\n";
    echo "var mrktx$lcnt = \"$inf[$lcnt]\";\n";
    echo "var infowindow$lcnt = new google.maps.InfoWindow({
        content: mrktx$lcnt
      });";
    echo "var marker$lcnt = new google.maps.Marker({position: point$lcnt, map: map});\n";
    // echo "google.maps.event.addListener(marker$lcnt, 
    //      'mouseover', function() {
    //        infowindow$lcnt.open(map,marker$lcnt);
    //       });\n";
    //  echo "google.maps.event.addListener(marker$lcnt, 
    //      'mouseout', function() {
    //        infowindow$lcnt.close(map,marker$lcnt);
    //       });\n";
}
?>
}
</script>
</head>


<body onload='load()'>

 <div id="map_canvas" style="width: 100%; height: 100%;margin: 0 0 0 0;"></div>
 

      

  
  

 <?php include ("footer.php"); ?>